language: node_js
node_js:
- '8'
- '9'
- '10'
cache:
  directories:
  - node_modules
script: npm run test:cov
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_KEY
  on:
    tags: true
    repo: NemProject/nem-library-ts
